version: '3.8'

services:
  my-app:
    build: .
    ports:
      - "7860:7860"
    env_file:
      - .env
    volumes:
      - .:/app
    command: ["chainlit", "run", "app.py", "--host", "0.0.0.0", "--port", "7860"]