version: '3.8'

services:
  my-app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/my-app
    command: chainlit run mem-app.py --host 0.0.0.0 --port 8000 -w
